title: Software for revealing magnetic structure.
social:
  name: Dmitry Morozov
  links:
    - https://www.facebook.com/profile.php?id=100004082021870
    - https://ru.linkedin.com/pub/dmitry-morozov/59/90a/794
    - https://github.com/dvmorozov 

exclude: manual, theory
include: theory/stars.html
